/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();

skycons.play();

$(function() {
     city_choose('Taipei City');

     $('#dropdown li').on('click', function() {
         $('button').text($(this).text());
         city_choose($(this).attr("id"));
     });

});

$( '#dropdown li' ).each(function( index,element) {
  city=$(element).text();
  $.getJSON('https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D"' + $(this).attr("id") + '")%20and%20u%3D%27c%27&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys'
    ,function(data){
    var currentTemperature=data.query.results.channel.item.condition.temp;
    $(element).text($(element).text()+"  "+ currentTemperature + " " + "℃");
  })
});



var skycons_state = function(day,weather){
  if(weather == 32 || weather == 36 || weather == 34){
    skycons.set(day, Skycons.CLEAR_DAY);
  }
    if(weather == 31 || weather == 33){
    skycons.set(day, Skycons.CLEAR_NIGHT);
  }
    if(weather == 30 || weather == 44){
    skycons.set(day, Skycons.PARTLY_CLOUDY_DAY);
  }
    if(weather == 29){
    skycons.set(day, Skycons.PARTLY_CLOUDY_NIGHT);
  }
    if(weather == 25 || weather == 26 || weather == 27){
    skycons.set(day, Skycons.CLOUDY);
  }
    if(weather ==3 || weather == 4 || weather == 8 || weather == 9 || weather == 10 || weather ==11 || weather ==12 || weather ==35 || weather ==37 || weather ==38 || weather ==39 || weather ==40 || weather ==45 || weather ==47){
    skycons.set(day, Skycons.RAIN);
  }
    if(weather == 6 || weather == 7 || weather == 18){
    skycons.set(day, Skycons.SLEET);
  }
    if(weather == 5 || weather == 13 || weather == 14 || weather ==15 || weather ==16 || weather ==17 || weather ==41 || weather ==42 || weather ==43 || weather ==46){
    skycons.set(day, Skycons.SNOW);
  }
    if(weather == 0 || weather == 1 || weather == 2 || weather ==23 || weather ==24){
    skycons.set(day, Skycons.WIND);
  }
    if(weather == 19 || weather == 20 || weather == 21 || weather ==22){
    skycons.set(day, Skycons.FOG);
  }
}


var city_choose = function(city){
$.getJSON(
  'https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D"' + city + '")%20and%20u%3D%27c%27&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys', {},
    function(data){

          console.log('data',data);
          $('.temperature').text(data.query.results.channel.item.condition.temp);
          $('.date').text(data.query.results.channel.item.forecast[0].date);
          $('.weather').text(': ' + data.query.results.channel.item.condition.text);

          $("thead > tr >th:nth-child(1)").text(data.query.results.channel.item.forecast[1].date);
          $("tr:nth-of-type(1) >td:nth-of-type(1)").text(data.query.results.channel.item.forecast[1].low + '-' + data.query.results.channel.item.forecast[1].high + "℃");
          $("thead > tr >th:nth-child(2)").text(data.query.results.channel.item.forecast[2].date);
          $("tr:nth-of-type(1) >td:nth-of-type(2)").text(data.query.results.channel.item.forecast[2].low + '-' + data.query.results.channel.item.forecast[2].high + "℃");
          $("thead > tr >th:nth-child(3)").text(data.query.results.channel.item.forecast[3].date);
          $("tr:nth-of-type(1) >td:nth-of-type(3)").text(data.query.results.channel.item.forecast[3].low + '-' + data.query.results.channel.item.forecast[3].high + "℃");

         skycons_state("today",data.query.results.channel.item.condition.code);
         skycons_state("day1",data.query.results.channel.item.forecast[1].code);
         skycons_state("day2",data.query.results.channel.item.forecast[2].code);
         skycons_state("day3",data.query.results.channel.item.forecast[3].code);

        }
    );
};
